services:
  db:
    build: .
    container_name: postgres_room_reservation
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'